### ISSUE TITLE
LinearProgress API

### ISSUE THREAD

**Issue by aforemny** [aforemny/elm-mwc#15]
**API:**
```elm
type alias LinearProgressConfig msg =
    { variant : LinearProgressVariant
    , reverse : Bool
    , closed : Bool
    , additionalAttributes : List (Html.Attribute msg)
    }

type LinearProgressVariant
    = Indeterminate
    | Determinate Float
    | Buffered Float Float

linearProgress : LinearProgressConfig msg -> Html msg

linearProgressConfig : LinearProgressConfig msg
```

**Comment by ropwareJB** [comment]
`LinearProgress` components render with a default width of 0, so they aren't displayed without intervention with `additionalAttributes` to declare a class, is there a nicer way that we can expose controlling the width (or styles) of the component?

Alternatively, you can set the width with a CSS selector component-wide;
```css
mwc-linear-progress {
  width: 50%;
}
```

**Comment by aforemny** [comment]
@Montycarlo I cannot reproduce that in the current demo. Removing that rule from `./demo/Demo/LinearProgress.elm` renders them full width.
