### ISSUE TITLE
Add demo

### ISSUE THREAD

**Issue by aforemny** [aforemny/elm-mwc#2]
We could write Elm modules for all files in `./material-components-web-components/demos`. For an example, compare `./material-components-web-components/demos/card.html` with `./demo/Card.elm`.

- [x] button
- [x] card
- [x] checkbox
- [x] chips
- [ ] dialog
- [x] fab
- [ ] formfield
- [x] icon
- [x] icon-toggle
- [x] linear-progress
- [ ] list
- [ ] menu
- [x] radio
- [x] ripple
- [ ] select
- [ ] slider
- [x] snackbar
- [x] switch
- [ ] tabs
- [x] textfield
- [ ] typography

**Comment by ropwareJB** [comment]
Is the aim to have actual pages emulating the demo for the `material-components-web-component` repo exactly, or just all on one page?
