### ISSUE TITLE
Self-Contained Component State at odds with Elm lifecycle

### ISSUE THREAD

**Issue by ropwareJB** [aforemny/elm-mwc#24]
The internal state of components are at odds with the state management of Elm.

Take `IconToggle` for example, with the following;
```
view =
    iconToggle
        { iconToggleConfig
            | on = True
            , icon = "sentiment_satisfied"
            , offIcon = "sentiment_neutral"
         }
```

Here, we're clearly setting the state of the `IconToggle` to *always* be on, however our web component manages its' own internal state, and will allow the user to toggle on/off despite our effort to force it to always be in the 'on' state.

Furthermore, even if we register a `onClick` event to update our Elm model and consequently re-run the `view` for the associated component, the Elm DOM detects no change, and thus does not update the component.

This is a pretty significant problem, as it severely hinders our ability to use components with self-contained state. It's very easy for our elm state to become desynchronized with the web component state.

**Comment by aforemny** [comment]
Hi @Montycarlo, thank you for raising this potential problem. I agree that the component's behavior is add odds with Elm's behavior.

There are two things ideally that I would like an Elm implementation to guarantee:
(1) If Elm's model does not change, then any interaction should not change the component's state.
(2) If Elm's model does change, then the components updates to reflect that change.

Your observations fall in the category of (1). As far as I could test it already, (2) seems to be guaranteed by the current implementation.

While I would ideally like (1) to be true, I am thinking that we can get away with (1'):
(1') If Elm correctly implements the intended behavior of the component, then Elm's representation and the component's state coincide throughout interaction.

In your examples, the Elm code does not implement the intended behavior of the component (if you click an icon toggle, it should toggle), and so it is not an exception from (1').

My point is that not guaranteeing (1) might no be too big of an issue in real application as (1') would hold. Does that make sense? What are your thoughts? :-)

**Comment by ropwareJB** [comment]
That seems like a good orientation - seems like that would be pretty achievable with the majority of what we have already, and coercing developers to attach listeners to component events.
