### ISSUE TITLE
Project development status and goals

### ISSUE THREAD

**Issue by ok32** [aforemny/elm-mwc#33]
Hey.
I'd like to learn what's the state of affairs here. Why did development stop six months ago? How do you see the future of this project? Is it dead or alive? ;)

Thank you.

**Comment by aforemny** [comment]
Hi @ok32,

sorry for the late reply. It turns out that this project is dead and I am focusing on another project instead. For some information, please refer to this comment: https://github.com/aforemny/elm-mdc/issues/112#issuecomment-515018036
