### ISSUE TITLE
 Discuss API

### ISSUE THREAD

**Issue by aforemny** [aforemny/elm-mwc#6]
Hi! While we work on the demo, I will add the API of each component to its own issue. Anybody feel free to share your thoughts there!

**Notes:**
- `additionalAttributes` is too verbose (`htmlAttrs`?)
- Consider exposing specific attributes, `class`, `width` or `style` (#15)?
- Should we use `Maybe` where configuration fields are optional? We wouldn't need to do that, since upstream defaults to `""`, `false`, etc. anyways..

**General:**
- Self-Contained Component State at odds with Elm lifecycle (#24)

**Components:**
- [ ] button (#8)
- [ ] card (#26)
- [ ] checkbox (#9)
- [ ] chips (#27)
- [ ] dialog (#10)
- [ ] fab (#11)
- [ ] formfield (#12)
- [ ] icon (#13)
- [ ] icon-toggle (#14)
- [ ] linear-progress (#15)
- [ ] list (#28)
- [ ] menu (#16)
- [ ] radio (#17)
- [ ] ripple (#18)
- [ ] select (#30)
- [ ] slider (#22)
- [ ] snackbar (#7)
- [ ] switch (#19)
- [ ] tabs (#20)
- [ ] textfield (#21)

**Comment by ropwareJB** [comment]
More generally, `additionalAttributes` is used to add more attributes, but it could be a lot shorter and more succinct. I'm not sure if that's more broadly the Elm convention, but consider one of the following;

- htmlAttrs
- attrs
- extra
