### ISSUE TITLE
Checkbox API

### ISSUE THREAD

**Issue by aforemny** [aforemny/elm-mwc#9]
**Notes:**
- What event handlers do we want in `CheckboxConfig`?
- What are use-cases for `value`?

**API:**
```elm
type alias CheckboxConfig msg =
    { state : State
    , disabled : Bool
    , value : String
    , additionalAttributes : List (Html.Attribute msg)
    }

type State
    = Unchecked
    | Checked
    | Indeterminate

checkboxConfig : CheckboxConfig msg

checkbox : CheckboxConfig msg -> Html msg
```

**Comment by SidneyNemzer** [comment]
> Should we combine fields checked, indeterminate into one?

I think so! What would happen if you have `{ checked = True, indeterminate = True }` anyway? A union type would prevent that from happening and it would better describe the possible states.

**Comment by aforemny** [comment]
@SidneyNemzer I added that in a9fcb5faa7d0737eb96cb11c44c150e24766fe7e.
